name: Build Custom V2ray Rules

on:
  schedule:
    - cron: '0 0 * * 1' # Запускать каждую неделю в понедельник
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: domain-list-community
          
      - name: Build custom geosite.dat
        run: |
          cd domain-list-community
          mkdir -p custom-data
          
          CATEGORIES="vk kinopoisk aviasales drweb wildberries rutube ozon wink 2gis kaspersky ok yandex okko avito mosmetro dzen mailru mailru-group category-travel-ru x5 category-gov-ru category-entertainment-ru category-retail-ru category-medicine-ru category-media-ru category-ecommerce-ru category-ru category-bank-ru"
          
          copy_with_deps() {
            local file=$1
            if [ -f "data/$file" ] && [ ! -f "custom-data/$file" ]; then
              cp "data/$file" "custom-data/"
              grep -Eo "^include:[a-zA-Z0-9_-]+" "data/$file" | cut -d':' -f2 | while read -r dep; do
                copy_with_deps "$dep"
              done
            fi
          }
          
          for cat in $CATEGORIES; do
            copy_with_deps "$cat"
          done
          
          rm -rf data
          mv custom-data data
          go run main.go --outputdir=../ --datapath=data/
          cd ..
          
          # Переименовываем dlc.dat в geosite.dat, так как компилятор назвал его по-своему
          if [ -f dlc.dat ]; then mv dlc.dat geosite.dat; fi
          
      - name: Download raw geoip texts
        run: |
          mkdir -p geoip-raw
          curl -sSL "https://raw.githubusercontent.com/v2fly/geoip/release/text/ru.txt" -o geoip-raw/ru.txt
          curl -sSL "https://raw.githubusercontent.com/v2fly/geoip/release/text/private.txt" -o geoip-raw/private.txt
          
      - name: Build custom geoip.dat
        run: |
          go install github.com/urlesistiana/v2dat@latest
          # Собираем geoip.dat
          ~/go/bin/v2dat pack geoip -o ./ -n geoip.dat geoip-raw/ru.txt geoip-raw/private.txt
          
      - name: Generate Release Notes
        run: |
          echo "Минималистичные сборки V2ray DAT файлов." > release.txt
          echo "Только нужные геосайты и geoip для максимальной экономии трафика при обновлении баз." >> release.txt
          
      - name: Publish to Github Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Удаляем старый релиз (если есть), чтобы всегда была свежая ссылка /latest/
          gh release delete latest --cleanup-tag -y || true
          
          # Заливаем файлы в раздел Releases
          gh release create "latest" geosite.dat geoip.dat -F release.txt -t "Lightweight Custom Rules"
